- pinger.go
for normal ping work the identifier should not exist or should be equal to an empty hash
> Fix Ping. Delete Identifier

- app.go
`Reply` messages were encoding by default `type` set to empty string and it was causing issues since the `type` if not present should be omitted.
> Omit empty type

- CHANGELOG.md
- Readme.md
- cli/cli.go
- cmd/anycable-go/main.go
- config/config.go
This PR adds ability to bind metrics server to another address. It will be helpful if you want to protect metrics with basic auth and reverse proxying
> Add ability to specify metrics host bind

- .circleci/config.yml
- Makefile
- Readme.md
- cmd/anycable-go/main.go
- metrics/custom_printer.go
- metrics/custom_printer_unsupported.go
- mrb/mrb.go
- mrb/mrb_test.go
- mrb/mrb_unsupported.go
From now on, we don't need to pass hacky CGO_ENABLED env variable
to disable mruby support. It means that it's possible to
install binary with convenient `go get` and it works for all
the users despite their platform specifics.
Besides, these more minor changes were made:
- default version value respects mruby support with `mrb` postfix
- changes are reflected in Makefile and CI
- removed useless `-installsuffix` argument for all build commands
> Use Golang specific build tag `mrb` to manage mruby feature

- metrics/counter.go
- metrics/gauge.go
- metrics/metrics.go
- metrics/metrics_test.go
- metrics/prometheus.go
It's not necessary to copy the whole sets of metrics when we want to read them in a bunch atomically. The proposed changes reduce the amount if unnecessary object allocations a little bit. In addition, metrics name and description has been protected from modification. There was a chance that a name could be changed but it preserved in the metric map which led to inconsistency.
>  Reduce the amount of object allocations during reading sets of metrics 

- .circleci/config.yml
- Makefile
Hi there,
Accidentally, I've noticed that the build process is not ideal - it produces not the smallest possible binaries.
I've fixed that in CI configuration and Makefile, refactored it a little bit.
Before:
```
10M	anycable-go-v0.6.0-preview5-27-gf7c7e77-freebsd-386
12M	anycable-go-v0.6.0-preview5-27-gf7c7e77-freebsd-amd64
10M	anycable-go-v0.6.0-preview5-27-gf7c7e77-freebsd-arm
12M	anycable-go-v0.6.0-preview5-27-gf7c7e77-linux-amd64
10M	anycable-go-v0.6.0-preview5-27-gf7c7e77-linux-arm
11M	anycable-go-v0.6.0-preview5-27-gf7c7e77-linux-arm64
10M	anycable-go-v0.6.0-preview5-27-gf7c7e77-macos-386
12M	anycable-go-v0.6.0-preview5-27-gf7c7e77-macos-amd64
10M	anycable-go-v0.6.0-preview5-27-gf7c7e77-win-386
12M	anycable-go-v0.6.0-preview5-27-gf7c7e77-win-amd64
```
After:
```
7.4M …
```
> Reduce binary size

- node/node.go
- node/session.go
According to [RFC6455](https://tools.ietf.org/html/rfc6455#section-7.4.2) it's not correct to use 3xxx close codes directly without registering in IANA. 
As far as I see ActionCable itself doesn't care too much about it. They have status code for abnormal status 
https://github.com/rails/rails/blob/61490805fe25091b080f5bba0e286716cdb56245/actioncable/lib/action_cable/connection/client_socket.rb#L42
And a success status (which i don't see to be used at all)
https://github.com/rails/rails/blob/master/actioncable/lib/action_cable/connection/client_socket.rb#L91-L98
I've refactored this logic a little bit a tried to find an appropriate status code for each case AC terminates websocket connections.
> Fix websocket close status to reflect the reason for the closure

- cmd/anycable-go/main.go
- node/disconnect_queue.go
- node/disconnect_queue_test.go
- node/hub.go
- node/session_test.go
Looking through the code I've found a couple of places where some more specific technics for synchronization makes more sense. In addition, I've fixed a potential deadlock on multiple `DisconnectQueue#Shutdown` invocations and add more tests.
> Use idiomatic constructions for synchronization, fix a potential deadlock

- CHANGELOG.md
- cli/cli.go
- config/config.go
- node/session.go
Fixes #30
Client message size is no longer hardcoded but can be set via command line option or env variable.
> Configurable max message size

- CHANGELOG.md
- node/session.go
- utils/utils.go
- utils/utils_test.go
If a load balancer standing in front of WebSocket server assigns `X-Request-ID` header,
this request ID will be used for session identification.
Heroku[ assigns ids to all requests](https://devcenter.heroku.com/articles/http-request-id).
For NGINX, this configuration is available for proxy-passed location:
```nginx
location /cable {
proxy_set_header X-Request-ID $request_id;
proxy_pass http://anycable;
}
```
> Use request id for session uids if available

- cli/cli.go
- cmd/anycable-go/main.go
- Add deprecation warning for default interface
- CLI args typo is fixed
- Order of CLI vars is aligned with docs for readability
> Fix cli args help, align vars order

- CHANGELOG.md
- utils/utils.go
- utils/utils_test.go
This is the first step to support remote connection address available with AnyCable.
There were three options to where `REMOTE_ADDR` cab be included:
❌ To GRPC protocol itself - too huge change with backward incompatibility. I put this idea aside to potentially more significant protocol changes. I'm thinking about maybe replacing `headers` completely with more generic CGI variables aka Rack Env. They have some nice conventions and are supported widely in different languages to build http request object.
❌ To GRPC message  metadata – requires more code changes to the existent code, can't be presented in all grpc requests like `sid`
✅ Synthetic header – perfect temporary solution at the moment
Symmetric change in RPC server https://github.com/anycable/anycable/pull/88
> Set `REMOTE_ADDR` synthetic header 

- Makefile
- cmd/gobench-cable/main.go
- gobench/gobench.go
- node/node.go
Pure Go implementation (w/o RPC) of [BenchmarkChannel](https://github.com/palkan/websocket-shootout/blob/master/ruby/action-cable-server/app/channels/benchmark_channel.rb) solely for benchmarking Go server functionality.
> Add gobench-cable binary

- CHANGELOG.md
- cli/cli.go
- rpc/config.go
- rpc/rpc.go
Improve gRPC performance and stability by getting rid of the connections pool in favor of the built-in streaming and multiplexing provided by the grpc package.
[Benchmarks](https://github.com/anycable/anycable-go/blob/master/cmd/rpcbench/main.go) show that using a single client result in less errors and slightly better performance than using a pool.
Also, retry mechanism has been also improved to handle exhausted and unavailable errors differently: when we receive ResourceExhausted we try to re-run the request almost immediately. The reason is that we assume that the concurrency settings for the client and the server are similar (though not equal, see below), thus, there could not be real exhaustion but the lag in server implementation (it looks like the worker is returned to the pool …
> Replace pool with single gRPC client

- .docker/Dockerfile.alpine-linux-amd64
- CHANGELOG.md
Fixes https://github.com/anycable/anycable-go/issues/92
The purpose of this pull request is to not use the `edge` version of alpine; as it is not [suitable for production environment](https://wiki.alpinelinux.org/wiki/Edge).
✅ Done. Let me know if it should be any different.
> docker: change alpine version to latest

- CHANGELOG.md
- Makefile
- common/common.go
- common/common_test.go
- node/hub.go
- node/node.go
- node/node_test.go
Handle remote commands sent via Pub/Sub. Currently, only remote disconnect is supported.
> Add remote commands support

- CHANGELOG.md
- Makefile
It seems the git ref version determination in the Makefile has gone missing, this PR simply adds it again.
> re-add git version to LD_FLAGS

- CHANGELOG.md
- common/common.go
- node/hub.go
- node/node.go
- node/session.go
Move message structs into common package.
Made pingMessage, disconnectMessage and Reply public members of the common package, together with their toJSON (now ToJSON) functions.
No - if tests still run, it worked. :)
> Externalize message structs into common package

- .github/workflows/test.yml
- MacOS and Linux binaries are built automatically for every commit from master
- Binaries for PRs are built iff "[Build]" string is present in the PR description (useful for public testing of experimental features or triages)
> CI: Build MacOS and Linux binaries for master and specified commits

- CHANGELOG.md
- docs/instrumentation.md
- metrics/gauge.go
- metrics/gauge_test.go
- metrics/metrics.go
- rpc/rpc.go
Add a metric to track the size of the RPC calls queue (`rpc_pending_num`). This metrics could be used in auto-scaling strategies.
> RPC pending calls metrics

- .github/workflows/lint.yml
- protocol/protocol.go
- protocol/protocol_test.go
- rpc/rpc.go
- rpc/rpc_test.go
Extract functionality which converts protobufs to internal structs and build protobufs.
This code could be used by future controllers.
- Added `protocol` package.
- Moved protobuf building and "parsing" from `rpc` to `protocol`.
> Extract protocol utils from rpc package

- metrics/counter.go
- metrics/counter_test.go
This PR fixes an issue where IntervalDelta is calculated incorrectly if there is no change to the counter between update interval.
Fixed it check the last value being zero instead delta being zero.
> Calculate IntervalDelta correctly if there are no changes to the counter

- CHANGELOG.md
- cli/cli.go
- node/config.go
- node/session.go
The anycable-go service sends the ping messages on websocket connections. The message itself is a unix timestamp in seconds. We want to use this timestamp information to calculate the perceived latency of the messages from client's perspective. However the timestamps in seconds do not provide the precision we need. The timestamps in milliseconds is more desirable. To make the change to milli seconds backward compatible, allow ping timestamp format to be configurable.
Added ping_timestamp_format config which takes the values of "ms" (milli seconds), "ns" (nano seconds) and "s" (seconds) with default "s". Based on the config specified, the ping messages will emit timestamps in milli seconds, nano seconds or seconds.
> Make ping timestamp format configurable

- CHANGELOG.md
- cli/options.go
- ws/config.go
- ws/handler.go
- ws/handler_test.go
Adds `--allowed_origins` option to enable Origin check during the WebSocket upgrade.
Closes #134
> Origin check

- CHANGELOG.md
- cli/cli.go
- cli/options.go
- config/config.go
- go.mod
- metrics/metrics.go
- server/server.go
- vendor/golang.org/x/net/netutil/listen.go
- vendor/modules.txt
This PR adds a new `--max-conn` config option to limit simultaneous server connections.
> Limit server connections with `--max-conn` config

- CHANGELOG.md
- cli/options.go
- docs/configuration.md
- rpc/config.go
- rpc/rpc.go
This allows anycable to be used with AWS ALB which requires HTTPS when
proxying gRPC.
I'm using a private ALB inside of an AWS VPC to proxy the gRPC traffic from websocket containers to anycable-rails containers. ALB doesn't allow the use of h2c and requires an HTTPS listener to be set up.
I've added a new configuration option named `--rpc_enable_tls` and modified the rpc initialization log message to notify the operator of the selected mode.
I wasn't sure what tests to add for testing TLS and cleartext traffic. I've bench tested both settings.
I've tested these changes in our staging environment with: https://github.com/outstand/docker-anycable-go
> Add --rpc_enable_tls option

- pubsub/redis.go
As a result of reviewing the code, I found a place with potential leaked connections to Redis, in a situation where the role is not correctly set for sentinel. As you can see connections will be lost as a result of reconnects until the GC comes back on or the application is quit.
I have not reproduced this situation as I am currently limited in time. But I think that it is possible to draw such a situation in mind and to draw the conclusions that I came to.
As a fix, I moved the delayed closing of the connection before checking the sentinel role, this ensures that after exit the connection will be closed.
> Fix defer Redis Connection Close before checking sentinel role

- CHANGELOG.md
- cli/options.go
- pubsub/redis.go
Skipping certificate validation for encrypted connection to Redis is not secure as it allows for man-in-the-middle attack.
However, given how troublesome it may be to set up SSL certificates properly, sometimes it should be disabled. Hence a setting for this.
- Changed default behavior from “not validate” to “validate” TLS certificate
- Added a setting to disable validation (`--redis_tls_verify` or `ANYCABLE_REDIS_TLS_VERIFY`)
> Validate Redis server TLS certificates by default, allow to disable

- .circleci/Gemfile
- .github/workflows/lint.yml
- .github/workflows/test.yml
- CHANGELOG.md
- Makefile
- broadcast/http.go
- broadcast/legacy_redis.go
- broadcast/redis.go
- broadcast/redis_test.go
- cli/options.go
- cli/runner_options.go
- docs/broker.md
- docs/configuration.md
- pubsub/redis.go
- redis/redis.go
Introduce a new broadcasting adapter using Redis Streams consumer groups. This adapter is meant to be used with a broker, since every message is processed by a single node from the cluster.
- Delete stale consumers automatically.
Every time we start a server, we create a new consumer group. On the server shutdown, we destroy the consumer group. However, if the server crashed unexpectedly, the consumer may stay on the list of consumers in Redis. We can implement automatic stale consumers deletion. For example, we can check for the stale consumers (how?) at the server start and destroy them.
- Instrumentation.
It can be useful to track the number of pending messages in the stream. However, this metric is per-cluster, so we need to figure out what's the best way to provide this information. …
> Redis X broadcaster

- CHANGELOG.md
- cli/cli.go
- cli/options.go
- cli/runner_options.go
- common/common.go
- docs/configuration.md
- docs/signed_streams.md
- features/metrics.testfile
- features/runner.rb
- features/turbo_rpc_less.testfile
- hub/gate_test.go
- identity/identity.go
- identity/identity_test.go
- node/config.go
- node/node.go
- node/node_test.go
- node/session.go
- node/session_test.go
- rails/cable_ready.go
- rails/cable_ready_test.go
- rails/turbo.go
- rails/turbo_test.go
Introduce disconnect modes, including "auto" mode which determines whether to perform Disconnect RPC calls per session.
- Added `DisconnectInterest` field to CallResult and CommandResult to indicate whether the client is interested in Disconnect callbacks. Currently, we only use this field in Identify and signed streams controllers, but the functionality can be extended to RPC calls as well.
- Extracted `node.Authenticated` to allow custom applications to register sessions without authenticating via RPC.
- Added `session.MarkDisconnectable(true | false)`.
> Disconnect modes

- CHANGELOG.md
- Makefile
- cli/options.go
- docs/configuration.md
- rpc/config.go
- rpc/http.go
- rpc/rpc.go
Partially implements #180
Allow to explicitly specify root certificate authority certificate to validate connection to gRPC server.
Config option and loading of certificate from either file or directly from provided string value.
Recommended usage:
1. Specify CA cert file path in the `rpc_tls_root_ca` command line option:
```sh
anycable-go --rpc_tls_root_ca /path/to/rootCA.pem --rpc_enable_tls true
```
2. Specify CA cert contents directly in the `ANYCABLE_RPC_TLS_ROOT_CA` env variable:
```sh
ANYCABLE_RPC_TLS_ROOT_CA="$(cat /path/to/rootCA.pem)" ./anycable-go --rpc_enable_tls true
```
Is it a good idea to check for file presence when there is whole few kilobyte long certificate chain presented in a string value?
> Allow to configure secure connection to RPC server

- CHANGELOG.md
- cli/cli.go
- cli/options.go
- docs/configuration.md
- features/shutdown.testfile
- hub/hub.go
- node/broker_integration_test.go
- node/config.go
- node/disconnect_queue.go
- node/disconnect_queue_test.go
- node/disconnector.go
- node/node.go
Make shutdown timeout configurable.
> feat: --shutdown_timeout

- CHANGELOG.md
- broker/broker.go
- cli/cli.go
- cli/options.go
- cli/session_options.go
- common/common.go
- docs/configuration.md
- etc/anyt/broker_tests/restore_test.rb
- features/ping.testfile
- features/ping_pong.testfile
- node/broker_integration_test.go
- node/config.go
- node/node.go
- node/node_mocks_test.go
- node/node_test.go
- node/session.go
- node/session_test.go
- server/request_info.go
- server/request_info_test.go
This PRs combines several improvements regarding server-client pings and session configuration.
> Ping-related improvements

- CHANGELOG.md
- cli/cli.go
- cli/options.go
- config/config.go
- docs/sse.md
- features/sse.testfile
- forspell.dict
- node/node.go
- node/session.go
- server/cors.go
- server/server.go
- sse/config.go
- sse/connection.go
- sse/connection_test.go
- sse/encoder.go
- sse/encoder_test.go
- sse/handler.go
- sse/handler_test.go
- sse/sse.go
This PR brings Server-Sent Events support to AnyCable making it possible to subscribe to Action Cable channel updates via EventSource or pure HTTP.
One of the primary use cases is to use Turbo Streams without Action Cable on the client side:
```html
<turbo-stream-source src="http://localhost:8080/events?turbo_signed_stream_name=chat_1" />
```
> SSE support

- CHANGELOG.md
- redis/config.go
- redis/config_test.go
Add support for REDIS_URL with trailing slash hostnames (`redis://localhost:6379/`)
Chomp trailing slash in the hostname
Upstream this change to `rueidis` URL parsing as the implementation doesn't tolerate the trailing slash hostnames (`redis-cli` does).
> Add support for REDIS_URL with trailing slash hostnames

- CHANGELOG.md
- Makefile
- broker/broker.go
- broker/memory.go
- broker/memory_test.go
- broker/nats.go
- broker/nats_test.go
- cli/cli.go
- cli/runner_options.go
- config/presets.go
- config/presets_test.go
- docs/configuration.md
- docs/reliable_streams.md
- enats/config.go
- enats/enats.go
- go.mod
- go.sum
- node/broker_integration_test.go
Add a broker implementation using NATS to store and distribute messages across nodes.
> NATS broker

- CHANGELOG.md
- rpc/config.go
- rpc/config_test.go
Return support for an scheme omitted IP address in RPC_HOST 
For example, `127.0.0.1:50051/anycable`.
It's missing from 1.4.6 which introduced auto RPC implementation
inferring from the RPC host.
Default to grpc:// scheme if omitted + test all known RPC_HOST variants + include invalid RPC_HOST to logs for better debugging:
`!!! RPC failed !!!, cause: unknown RPC implementation: <invalid RPC host: invalid://:+>`
> Return support for an scheme omitted IP address in RPC_HOST 

- broadcast/http.go
- broker/memory.go
- broker/nats.go
- cli/options.go
- common/common.go
- docs/signed_streams.md
- etc/anyt/broadcast_tests/whisper_test.rb
- hub/gate.go
- node/broker_integration_test.go
- node/node.go
- node/node_test.go
- streams/config.go
- streams/controller.go
- streams/controller_test.go
Add new `whisper` command support to publish messages from clients without using a server.
Inspired by [Laravel Echo](https://laravel.com/docs/11.x/broadcasting#client-events).
- Added `node.Whisper()` method to process `"type":"whisper"`  commands
- Added support for transient broadcast messages (not stored in the history)
- Added whispering support to pub/sub streams.
> Whispering
